name: chat_box
description: A new Flutter chat box application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^3.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^1.1.0
  connectivity: ^3.0.3
  permission_handler: ^6.1.1
  path_provider: ^2.0.1
  provider: ^5.0.0
  retrofit: ^1.3.4
  dio: ^3.0.10
  intl: ^0.16.1
  uuid: ^2.2.2
  freezed_annotation: ^0.12.0

  data_connection_checker: ^0.3.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.18.0
  build_runner: ^1.7.3
  json_serializable: ^3.0.0
  retrofit_generator: ^1.3.8+1
  freezed: ^0.12.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
